"""empty message

Revision ID: 191d7004a675
Revises: 807abcfdec2a
Create Date: 2025-10-24 22:31:42.230047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191d7004a675'
down_revision = '807abcfdec2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Members', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
