"""empty message

Revision ID: 231969eafd04
Revises: 
Create Date: 2025-10-14 13:39:32.972102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231969eafd04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Appointments',
    sa.Column('appointment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['Members.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['Members.id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('Department',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Members.id'], ),
    sa.PrimaryKeyConstraint('doctor_id')
    )
    op.create_table('Treatment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('visittype', sa.Text(), nullable=True),
    sa.Column('testdone', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['Appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['Members.id'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'patient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Treatment')
    op.drop_table('Department')
    op.drop_table('Appointments')
    op.drop_table('Members')
    # ### end Alembic commands ###
