"""empty message

Revision ID: 59fa4fd26870
Revises: 2b9c1e228109
Create Date: 2025-10-10 18:03:34.120662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fa4fd26870'
down_revision = '2b9c1e228109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.drop_column('patinet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patinet_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
