"""empty message

Revision ID: 5cfad4d64c4a
Revises: cbdf4656add5
Create Date: 2025-10-05 23:12:19.834081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfad4d64c4a'
down_revision = 'cbdf4656add5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.Text(), nullable=False))
        batch_op.drop_column('userename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userename', sa.TEXT(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
