"""empty message

Revision ID: 69f427996182
Revises: 5cfad4d64c4a
Create Date: 2025-10-05 23:48:55.692330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f427996182'
down_revision = '5cfad4d64c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
