"""empty message

Revision ID: 750919b295d4
Revises: 69f427996182
Create Date: 2025-10-05 23:51:33.600674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750919b295d4'
down_revision = '69f427996182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
