"""empty message

Revision ID: 807abcfdec2a
Revises: 
Create Date: 2025-10-21 21:39:03.739115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807abcfdec2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['Members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Availability')
    # ### end Alembic commands ###
