"""empty message

Revision ID: cbdf4656add5
Revises: 
Create Date: 2025-10-05 23:11:03.542926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdf4656add5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userename', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Doctors')
    # ### end Alembic commands ###
