"""empty message

Revision ID: f93e56453162
Revises: 750919b295d4
Create Date: 2025-10-06 09:25:44.082659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93e56453162'
down_revision = '750919b295d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
